/**
 * Production entry point.
 *
 * One process serves both the API and the web app on one port. That is the fix for #9: v1
 * ran Express on 3000 and SvelteKit on 5173 with an `hooks.server.js` proxy between them
 * that lived at the repo root, where SvelteKit never compiled it — so `/api/*` returned
 * 404 for anyone who opened the app by IP address instead of `localhost`.
 *
 * With no proxy there is nothing to be in the wrong place, and no CORS layer to
 * misconfigure.
 *
 * The SvelteKit handler is imported dynamically so the module graph only reaches for
 * `build/handler.js` when it actually exists, which lets the API be started on its own
 * without a build step.
 */

import type { NextFunction, Request, Response } from 'express';
import { createService, installSignalHandlers } from './lib/server/index.js';
import { fatal } from './lib/server/logger.js';

type SvelteKitHandler = (req: Request, res: Response, next: NextFunction) => void;

async function loadWebHandler(log: {
  info: (obj: object, msg: string) => void;
}): Promise<SvelteKitHandler | null> {
  // The specifier is held in a variable so TypeScript treats the import as dynamic and
  // untyped: `build/` is generated by `vite build`, is not in the repository, and must stay
  // optional so the API can run on its own.
  const specifier = '../build/handler.js';

  try {
    const module = (await import(specifier)) as { handler?: SvelteKitHandler };
    return module.handler ?? null;
  } catch (error) {
    // Expected when running the API without a SvelteKit build (tests, `npm run dev:api`).
    log.info(
      { reason: error instanceof Error ? error.message : String(error) },
      'no SvelteKit build found, serving the API only'
    );
    return null;
  }
}

async function main(): Promise<void> {
  const service = createService();
  installSignalHandlers(service);

  const webHandler = await loadWebHandler(service.log);

  if (webHandler) {
    service.log.info('mounting the SvelteKit handler for every non-/api route');
    service.app.use(webHandler);
  }

  await service.listen();
}

main().catch((error: unknown) => {
  fatal('failed to start', error);
  process.exit(1);
});
